opt_in_rules:
  - closure_end_indentation
  - closure_spacing
  - conditional_returns_on_newline
  - empty_count
  - first_where
  - force_unwrapping
  - implicit_return
  - let_var_whitespace
  - multiline_parameters
  - nimble_operator
  - no_extension_access_modifier
  - operator_usage_whitespace
  - redundant_nil_coalescing
  - vertical_parameter_alignment_on_call

included:
  - SimpleBudget
  - SimpleBudgetTests

function_body_length:
  warning: 50

trailing_comma:
  mandatory_comma: true

identifier_name:
  min_length:
    error: 3 
  excluded:
    - id