version: 2
jobs:
  build-and-test:
    macos:
      xcode: "10.0.0"
    working_directory: /Users/distiller/SimpleBudget
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: test
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - restore_cache:
          keys:
            - carthage-cache-{{ checksum "Cartfile.resolved" }}
      - run: ./bin/bootstrap-if-needed
      - save_cache:
          key: carthage-cache-{{ checksum "Cartfile.resolved" }}
          paths:
            - Carthage
      - run: bundle install
      - run:
          name: Fastlane
          command: bundle exec fastlane $FASTLANE_LANE
      - store_artifacts:
          path: output
      - store_test_results:
          path: output/scan

workflows:
  version: 2
  build-test:
    jobs:
      - build-and-test